// card_styles.js
import { Dimensions, StyleSheet } from 'react-native'
import Theme from '../Theme/theme'

const windowWidth = Dimensions.get('window').width

const card_styles = StyleSheet.create({
  card: {
    backgroundColor: Theme.white,
    // borderWidth: .5,
    // paddingBottom: 7,
    borderRadius: 10,
    marginTop: 2,
    marginBottom: 10,
    marginLeft: 'auto',
    marginRight: 'auto',
    shadowColor: Theme.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    width: '92%',
    // justifyContent: 'center'
  },
  cardHeader: {
    flexDirection: 'row',
    borderRadius: 8,
  },
  cardHeaderLeft: {
    width: '22%',
    // margin: 8,
    marginRight: 0,
    // borderWidth: 1,
  },
  truckIconContainer: {
    height: 70,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginTop: 10
    // borderWidth:1,
    // borderColor:'red'
    // width: '85%',
    // alignItems: 'center',
    // justifyContent: 'center',
    // width: 120,
    // backgroundColor: Theme.silver,
    // borderWidth: .5,
    // overflow: 'hidden',
  },
  speedInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    // marginTop: -8,
    // borderWidth: .5,
  },
  speedInfoText: {
    fontSize: Theme.font.medium,
    color: Theme.secondary,
    fontWeight: Theme.font.xthin,
    // paddingTop: 16,
    lineHeight: 18,
    // marginRight:10,
    // textAlign:'center'
  },

  cardHeaderRight: {
    flex: 1,
    borderWidth: 0,
    margin: 8,
    marginLeft: 0,
    // paddingLeft: 10,
    paddingHorizontal: 10


    // width:"30%"
  },

  numberPlate: {
    flexDirection: 'row',
    height: 25,
    backgroundColor: Theme.transparent,
    // backgroundColor: Theme.numplate,
    // backgroundColor: Theme.transparent,
    // elevation: 4,
    // alignItems: 'center',
    // justifyContent: 'center',
    // borderColor: Theme.black,
    borderRadius: 6,
    // marginRight: 8,
    marginBottom: 2,
    gap: 15,
    width: '100%',
    // marginLeft: 4,
    // borderWidth: .5,
    // marginTop: 8,
    justifyContent: 'space-between',
    alignItems: 'center',
    // justifyContent: 'center',
  },
  numberPlateText: {
    fontSize: 18,
    color: Theme.blue.primary,
    fontWeight: Theme.font.xxbold,
  },
  personal: {
    // backgroundColor: Theme.white,
  },
  indIcon: {
    alignItems: 'center',
  },
  wheel: {
    color: Theme.blue.gradient.all.start,
    backgroundColor: '#DDDDDD',
    width: 10,
  },
  indText: {
    color: Theme.white,
    fontSize: 8,
  },
  indText2: {
    color: Theme.blue.gradient.all.start,
  },

  address: {
    flexDirection: 'row',
    height: 46,
    overflow: 'hidden',
    // justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  addressText: {
    color: '#737373',
    fontSize: Theme.font.medium,
    marginTop: 5,
    lineHeight: 18,
    fontWeight: Theme.font.xthin,
    color: '#333322',
    // width: windowWidth / 1.95,
    // paddingLeft: 5,
    overflow: 'hidden',
    // borderWidth:1,
    // borderColor:'red',
    width: '90%',
  },
  runningStatus: {
    // flexDirection: 'row',
    // alignContent: 'center',
    // width: "100%",
    // paddingLeft: 5,
    // marginTop: 3,
    // width: windowWidth / 1.62,
    // justifyContent: 'center',
    // alignSelf: "center",
    // borderWidth: .5,
    // borderColor:'green',
  },
  linearGradient: {
    height: 20,
    justifyContent: 'center',
    borderRadius: 6,
    // marginRight: 10,
  },
  runningStatusText: {
    color: Theme.white,
    fontSize: 12,
    paddingLeft: 10,
    paddingRight: 10,
  },
  statusText: {
    color: '#333322',
    fontSize: 12,
    alignSelf: 'center',
    fontWeight: Theme.font.fat,
    lineHeight: 18,
  },
  addressMarker: {
    paddingRight: 6,
    // borderWidth: .5,
    // width: '10%',
    color: Theme.blue.primary,
  },
  iconFrame: {
    borderWidth: 2,
    borderRadius: 4,
    borderColor: '#f7f7f7',
    shadowColor: '#f7f7f7',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 1,
    width: 25,
    height: 25,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    // position: "relative",
    overflow: 'hidden',
  },
  satellite: {
    fontSize: 5,
    position: 'absolute',
    bottom: 1,
    right: 1,
  },

  statusBox: {
    flexDirection: 'row',
    gap: 5,
    alignItems: 'center',
    marginLeft: 5,
    borderWidth: 2,
    borderColor: '#f7f7f7',
    borderRadius: 5,
    shadowColor: '#f7f7f7',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 1,
    // paddingLeft: 5,
    paddingHorizontal: 2
    // justifyContent: 'center',
    // width: '98%',
    // justifyContent: 'space-between',
    // borderWidth:1
  },
  updatedText: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    fontSize: 12,
    color: '#333322',
    // borderWidth: 2,
    // borderColor: '#f7f7f7',
    // borderRadius: 5,
    // shadowColor: '#f7f7f7',
    // shadowOffset: { width: 0, height: 0 },
    // shadowOpacity: 1,
    // shadowRadius: 1,
    // paddingLeft: 5
    // padding: 5,
    // height: 25,
  },

  bottomInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent:'center',
    justifyContent: 'space-between',
    marginTop: -2,
    // borderWidth: .5,
    paddingHorizontal: 5,
  },
  bottomImg: {
    // position: 'absolute',
    // left: 4,
    // bottom: -4,
    marginRight: 10,
  },
  bottomTextContainer: {
    // flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 5,
    color: '#333322',
    borderWidth: 2,
    borderColor: '#f7f7f7',
    borderRadius: 5,
    shadowColor: '#f7f7f7',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 1,
  },
  bottomText: {
    fontSize: 12,
    paddingLeft: 6,
    paddingRight: 4,
  },
  kmTextContainer: {
    backgroundColor: '#113870',
    borderRadius: 3,
    borderWidth: 2,
    borderColor: '#113870',
  },
  kmText: {
    color: Theme.white,
    padding: 1,
    fontSize: Theme.font.small,
  },

  daysIconBox: {
    alignItems: 'center',
    flexDirection: 'row',
    paddingLeft: 5,
    color: '#333322',
    borderWidth: 2,
    borderColor: '#f7f7f7',
    borderRadius: 5,
    shadowColor: '#f7f7f7',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 1,
    marginRight: 5,
  },
  calanderDays: {
    fontSize: Theme.font.small,
    paddingLeft: 2,
    paddingRight: 2,
  },
  peg: {
    position: 'absolute',
    left: -10,
    width: '18%',
    backgroundColor: '#133970',
    zIndex: 0,
    marginBottom: 10,
    borderRadius: 4,
    alignItems: 'center',
    shadowColor: '#333',
    shadowOffset: { width: -3, height: 4 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 0,
  },
  halfBox: {
    // top: 6,
  },
  halfBox2: {
    top: 23,
  },
  halfBox3: {
    top: 40,
  },
  peg_text: {
    fontSize: 8,
    color: Theme.white,
    height: 12,
  },
  imei: {
    fontSize: Theme.font.xsmall,
    position: 'relative',
    bottom: -10,
  },
  hr_line: {
    marginTop: 7,
    borderWidth: 1,
    height: 2,
    backgroundColor: '#F7F7F7',
    borderColor: '#F7F7F7',
    width: '95%',
    alignSelf: 'center',
    marginBottom: 3,
  },
  share_box: {
    // borderWidth: 1,
    // height: 30,
    // position: 'absolute',
    // bottom: 0,
    // flex: 1,
    width: '100%',

    alignSelf: 'center',
    flexDirection: 'row',
    flexGrow: 1,
    justifyContent: 'space-around',
    backgroundColor: '#ebf2fc',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    paddingVertical: 5,
    marginTop: 5,
    // borderWidth: .5,
    // elevation: 10
    // justifyContent:'center',
    // alignItems: 'center',
  },
  bottom_icon_box: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottom_icon_text: {
    fontSize: Theme.font.xsmall,
    fontWeight: Theme.font.xxbold,
    color: Theme.blue.primary,
  },
})

export default card_styles
